### ISSUE TITLE
hbase connection error 

### ISSUE THREAD

**Issue by StartFeng** [Terry-Mao/bfs#51]
这两天测试bfs，发现directory模块连接hbase 出现错误如下：
read tcp 192.168.1.23:60518->192.168.1.193:9090: i/o timeout

为定位问题在hbase_test.go中加了两个TestCase，发现从bfs pool 获取的连接会出现此问题，直接用thrift api 则不会
import (
	"bfs/directory/conf"
	hbase "bfs/directory/hbase/hbasethrift"
	"bfs/libs/meta"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
	"net"
	"os"
	"testing"
	"time"
）
func TestOriginal(t *testing.T) {
	logformatstr_ := "----%s\n"
	logformatstr := "----%s 用时:%d-%d=%d毫秒\n\n"
	logformattitle := "建立连接"
	rowkey := "vim.gif"
	temptable := "bucket_test"
	protocolFactory := thrift.NewTBinaryProtocolFactoryDefault()
	transport, err := thrift.NewTSocketTimeout(net.JoinHostPort(HOST, PORT), 10*time.Second)
	if err != nil {
		fmt.Fprintln(os.Stderr, "error resolving address:", err)
		os.Exit(1)
	}
	client := hbase.NewTHBaseServiceClientFactory(transport, protocolFactory)
	if err := transport.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to "+HOST+":"+PORT, " ", err)
		os.Exit(1)
	}

	//client, err := hbasePool.Get()
	//if err != nil {
	//	fmt.Println(err)
	//}
	//--------------Exists
	logformattitle = "调用Exists方法"
	fmt.Printf(logformatstr_, logformattitle)
	tmpstartTime := currentTimeMillis()
	//
	isexists, err := (client.Exists([]byte(temptable), &hbase.TGet{Row: []byte(rowkey)}))
	fmt.Printf("rowkey{%s} in table{%s} Exists:%t\t", rowkey, temptable, isexists)
	if err != nil {
		fmt.Printf("Exists err:%s\n", err)
	}
	fmt.Println("")
	tmpendTime := currentTimeMillis()
	fmt.Printf(logformatstr, logformattitle, tmpendTime, tmpstartTime, (tmpendTime - tmpstartTime))
}

func TestPoll(t *testing.T) {
	logformatstr_ := "----%s\n"
	logformatstr := "----%s 用时:%d-%d=%d毫秒\n\n"
	logformattitle := "建立连接"
	rowkey := "vim.gif"
	temptable := "bucket_test"

	client, err := hbasePool.Get()
	if err != nil {
		fmt.Println(err)
	}
	//--------------Exists
	logformattitle = "调用Exists方法"
	fmt.Printf(logformatstr_, logformattitle)
	tmpstartTime := currentTimeMillis()
	//
	isexists, err := (client.Exists([]byte(temptable), &hbase.TGet{Row: []byte(rowkey)}))
	fmt.Printf("rowkey{%s} in table{%s} Exists:%t\t", rowkey, temptable, isexists)
	if err != nil {
		fmt.Printf("Exists err:%s\n", err)
	}
	fmt.Println("")
	tmpendTime := currentTimeMillis()
	fmt.Printf(logformatstr, logformattitle, tmpendTime, tmpstartTime, (tmpendTime - tmpstartTime))
}

func currentTimeMillis() int64 {
	return time.Now().UnixNano() / 1000000
}

运行结果：
=== RUN   TestOriginal
----调用Exists方法
rowkey{vim.gif} in table{bucket_test} Exists:false
----调用Exists方法 用时:1461205438652-1461205438636=16毫秒

--- PASS: TestOriginal (0.04s)
=== RUN   TestPoll
----调用Exists方法
rowkey{vim.gif} in table{bucket_test} Exists:false	Exists err:read tcp 192.168.1.23:60518->192.168.1.193:9090: i/o timeout

----调用Exists方法 用时:1461205439683-1461205438682=1001毫秒

--- PASS: TestPoll (1.03s)

**Comment by StartFeng** [comment]
找到原因了，我们的hbase thrift server 没有使用TFramedTransport协议

**Comment by Terry-Mao** [comment]
OK：）

**Comment by Terry-Mao** [comment]
这块我们会尽快使用原生的HBase client 替换
