### ISSUE TITLE
store.toml 配置数据类型不匹配

### ISSUE THREAD

**Issue by shanggl** [Terry-Mao/bfs#58]
NewCofnig("./store.toml") error(Type mismatch for 'conf.Config.Limit' : Type mismatch for 'conf.Limit.Delete' : Type mismatch for 'conf.Rate.Rate' : Expected float but found 'int64'.)

貌似是更新了config.go 之后，原来的 store.toml 未更新，是否需要一并更新？

**Comment by Terry-Mao** [comment]
好，我会更新一个大版本出来，马上修复，刚好修复之前的一些问题，今晚发布

**Comment by Terry-Mao** [comment]
修复了，看最新的tag
