### ISSUE TITLE
directory 中的 volume ，group，store这些内存信息不需要加锁么

### ISSUE THREAD

**Issue by shenwen2012** [Terry-Mao/bfs#59]
在directory 中的STORE  GROUP  VOLUME内存信息 在syncZookeeper go route 中定时更新，和在应用操作api 的go route 中使用这些公共内存资源 不需要加锁么？

**Comment by Terry-Mao** [comment]
COW Copy-on-Write，使用变量指向原子替换

**Comment by Terry-Mao** [comment]
比如 对象A-> 内存地址A，对象A->内存地址B；   对象A是8字节，一般64bit下，是原子赋值的；

**Comment by shenwen2012** [comment]
明白了，谢谢
