### ISSUE TITLE
所有的卷信息都存放在zk 里面，要是有上万个卷，zk 受得了么

### ISSUE THREAD

**Issue by shenwen2012** [Terry-Mao/bfs#60]
目前所有的卷 和 机器 和组信息都存放在zk 里面，如果这些信息要是足够多的话，zk 是不是会成为瓶颈？我对zk 了解得不够深入，无法完全评估，所有想咨询一下你们的考虑。

**Comment by Terry-Mao** [comment]
这个问题我们之前想过，有几个方案你可以参考下：
zk写入不算密集的化，压力还好，我们倒是读多写少；

1. 首先是block按照8字节对齐，可以考虑更大比如256，这样来减少Volume的数量；
2. zk 使用Observer来优化读性能；
3. 从业务隔离层面来考虑拆分成N多小集群；比如业务A用bfs-1 域名，业务B用bfs-2域名；
4. 机器规模在千台，每台20T计算，总量在20PB，大概是Facebook的规模，算了一下Volume大概在50万，这个量级查询确实会有压力了，我觉得可以考虑在proxy层做sharding；

问题都不大，可以比较好解决；

**Comment by shenwen2012** [comment]
谢谢解答，希望后面我也能给bfs贡献

**Comment by Terry-Mao** [comment]
欢迎PR，和讨论

**Comment by zhangjunfang** [comment]
工作中使用的zk  以及etcd   我建议使用etcd。其中zk在使用过程发现以下bug到现在还没有修复

**Comment by Terry-Mao** [comment]
目前我们线上使用zk正常跑了接近一年，请问你的zk遇到的bug是什么？etcd确实是更优的选择，因为我们更熟悉zk，后续会考虑etcd
