### ISSUE TITLE
upload到store中，部分失败如何处理？

### ISSUE THREAD

**Issue by yongzhizhan** [Terry-Mao/bfs#68]
我看到在proxy中，文件上传的逻辑，是通过directory获取stores，然后遍历stores，将文件上传到volume对应的store中，如果部分上传到失败，会直接返回，这样是不是会有文件残留，使得各个volume大小不同，会导致有些volume已经写满，有些未写满的状况出现？

我看了volume中的compact逻辑，貌似里面对于删除了的文件，直接跳过，不写入新的volume中，没对多个volume中，文件差异进行处理。

可能调查不是很详细，先假定是这样的流程，我想问一下，有很多时候，网络稍微不大稳定，很容易出现写入的失败的情况，这样是不是导致文件残留现象比较频繁出现？我可以怎样处理这个问题呢？

	params = url.Values{}
	for _, host = range res.Stores {
		params.Set("key", strconv.FormatInt(res.Key, 10))
		params.Set("cookie", strconv.FormatInt(int64(res.Cookie), 10))
		params.Set("vid", strconv.FormatInt(int64(res.Vid), 10))
		uri = fmt.Sprintf(_storeUploadApi, host)
		if err = Http("POST", uri, params, buf, &sRet); err != nil {
			return
		}
		if sRet.Ret != 1 {
			log.Errorf("http.Post store sRet.Ret: %d  %s %d %d %d", sRet.Ret, uri, res.Key, res.Cookie, res.Vid)
			err = errors.ErrInternal
			return
		}
	}
	if res.Ret == errors.RetNeedleExist {
		err = errors.ErrNeedleExist
	}
	log.Infof("bfs.upload bucket:%s filename:%s key:%d cookie:%d vid:%d", bucket, filename, res.Key, res.Cookie, res.Vid)
	return

**Comment by Terry-Mao** [comment]
非常不错的问题，我们是这样考虑的：

1. 首先内网异常或者节点之前的故障，不会那么的频繁，如果真有节点出问题，pitchfork模块也会主动设置volume为只读状态；
2. 这类“ghost file”，我觉得可以考虑打印日志或者某类方式扫描来定期清理，不过我们暂时是忽略的，因为量级肯定不会多；
3. TODO 优化，这里可以使用errgroup.Do 并行上传减少延迟

@zhapuyu
