### ISSUE TITLE
打开super block文件时，为什么没有采用O_APPEND？

### ISSUE THREAD

**Issue by codingfarmmer** [Terry-Mao/bfs#75]
您好，了解下，在打开super block文件，用于写needles时，为什么没有使用o_append，是考虑的store是单进程不存在并发写的原因吗？谢谢。

func NewSuperBlock(file string, c *conf.Config) (b *SuperBlock, err error) {
	b = &SuperBlock{}
	b.conf = c
	b.File = file
	b.closed = false
	b.write = 0
	b.syncOffset = 0
	b.Padding = needle.PaddingSize
	if b.w, err = os.OpenFile(file, os.O_WRONLY|os.O_CREATE|myos.O_NOATIME, 0664); err != nil {
		log.Errorf("os.OpenFile(\"%s\") error(%v)", file, err)
		b.Close()
		return nil, err
	}
	if b.r, err = os.OpenFile(file, os.O_RDONLY|myos.O_NOATIME, 0664); err != nil {
		log.Errorf("os.OpenFile(\"%s\") error(%v)", file, err)
		b.Close()
		return nil, err
	}
	if err = b.init(); err != nil {
		log.Errorf("block: %s init() error(%v)", file, err)
		b.Close()
		return nil, err
	}
	return
}

**Comment by Terry-Mao** [comment]
单进程但是内部是多goroutine的，加锁处理了，有不少东西需要同步操作
