### ISSUE TITLE
“unrecognized import path” with go get

### ISSUE THREAD

**Issue by Maybrittnelson** [Terry-Mao/bfs#78]
![image](https://user-images.githubusercontent.com/20365012/46252765-f2f84080-c49f-11e8-9e2f-b222d47c6c8d.png)
![image](https://user-images.githubusercontent.com/20365012/46246062-90189200-c42a-11e8-9b5a-63f88b1cc367.png)
### Any steps to reproduce the behavior?
Install the Go Tools
![image](https://user-images.githubusercontent.com/20365012/46252720-5635a300-c49f-11e8-8f33-365d1e7a2e90.png)
set GOROOT and GOPATH env in ~/.bash_profile
![image](https://user-images.githubusercontent.com/20365012/46252730-82e9ba80-c49f-11e8-8ff9-f3aa91458c99.png)

**Comment by ltzMaxwell** [comment]
You can just move bfs/ to $GOPATH/src fom simplicity.
